# Generated by Django 3.1.3 on 2021-05-27 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('image', models.CharField(default='', max_length=500, verbose_name='封面')),
                ('video_type', models.CharField(choices=[('1', '热血'), ('2', '冒险'), ('3', '搞笑'), ('4', '运动'), ('5', '竞技'), ('6', '剧情'), ('7', '穿越'), ('8', '青春'), ('9', '小说改'), ('10', '后宫'), ('11', '校园'), ('12', '励志'), ('13', '恋爱'), ('14', '百合')], max_length=100, verbose_name='视频类别')),
                ('nationality_type', models.CharField(choices=[('1', '中国'), ('2', '日本'), ('3', '韩国'), ('4', '其他')], max_length=100, verbose_name='国家')),
                ('info', models.TextField(verbose_name='简介')),
                ('mood', models.IntegerField(default=0, verbose_name='人气')),
                ('hav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('status', models.BooleanField(default=True, verbose_name='是否可以观看')),
                ('start_time', models.DateTimeField(verbose_name='开播')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
            },
        ),
        migrations.CreateModel(
            name='VideoSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('url', models.CharField(max_length=500, verbose_name='地址')),
                ('number', models.IntegerField(default=1, verbose_name='集数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sub', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '集数',
                'verbose_name_plural': '集数',
            },
        ),
        migrations.CreateModel(
            name='VideoStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_star', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '声优',
                'verbose_name_plural': '声优',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('comment', models.TextField(verbose_name='用户评论')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='videos.video', verbose_name='视频')),
                ('video_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_comment', to='videos.videosub', verbose_name='视频集数')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论',
            },
        ),
    ]
