# Generated by Django 3.1.3 on 2021-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='nationality_type',
            field=models.CharField(choices=[('1', '中国'), ('2', '日本'), ('3', '韩国'), ('4', '其他')], max_length=100, verbose_name='国家'),
        ),
    ]
