# Generated by Django 3.1.3 on 2021-05-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210525_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosub',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_sub', to='videos.video', verbose_name='视频'),
        ),
    ]
