# Generated by Django 3.1.3 on 2021-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210525_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostar',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_star', to='videos.video', verbose_name='视频'),
        ),
    ]
