# Generated by Django 3.1.3 on 2021-05-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20210528_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='sub',
            field=models.IntegerField(default=1, verbose_name='集数'),
        ),
    ]
