# Generated by Django 3.1.3 on 2021-05-29 22:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0012_auto_20210528_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoProgress',
            new_name='VideoHistory',
        ),
        migrations.AlterModelOptions(
            name='videohistory',
            options={'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
    ]
